### ISSUE TITLE
Question: how to attach relationship model?

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-seeder-plugin#2]
how would you attach a category and few tags to a blogpost?

**Comment by jonasva** [comment]
I had a similar issue, you can follow the[ Laravel docs](https://laravel.com/docs/5.4/database-testing#relationships) for that. 

eg:

```
$users = factory(App\User::class, 3)
           ->create()
           ->each(function ($u) {
                $u->posts()->save(factory(App\Post::class)->make());
            });
```

**Comment by chrisvidal** [comment]
thanks

**Comment by tobias-kuendig** [comment]
Thank you @jonasva for providing an example.
