### ISSUE TITLE
Make available on packagist

### ISSUE THREAD

**Issue by jonasva** [OFFLINE-GmbH/oc-seeder-plugin#5]
Would be good if this package was available on packagist as well so we can easily install it with composer. I saw a lot of your [other packages](https://packagist.org/packages/offline/?) are already on there. 

I've installed it directly from this repository for now:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/OFFLINE-GmbH/oc-seeder-plugin"
        }
    ],
    "require-dev": {
        "offline/oc-seeder-plugin": "~1.0.5"
    },
```

**Comment by tobias-kuendig** [comment]
It is now available here:
https://packagist.org/packages/offline/oc-seeder-plugin

Thank you for this suggestion!
