### ISSUE TITLE
--plugins option not works

### ISSUE THREAD

**Issue by meesiris** [OFFLINE-GmbH/oc-seeder-plugin#6]
--plugins option to run only specified seeders not works because strtolower().

php artisan plugin:seed --plugins=Vendor.PluginA,Vendor.PluginB --fresh

https://github.com/OFFLINE-GmbH/oc-seeder-plugin/blob/f37e06fb76243864babafc02d25fb785ecf59f93/classes/SeederManager.php#L39

**Comment by tobias-kuendig** [comment]
This is fixed vin v1.0.6, thanks
